### ISSUE TITLE
Input type error

### ISSUE THREAD

**Issue by kevinshaji97** [OWASP/SecureTea-Project#229]
**About the bug**
The Input  ``` Do you want to use the saved configuratons? (Y/y): ``` is not accepting strings (y or n) but digits 0 and 1 are accepted.

**To Reproduce**
1. Setup the configurations using a text editor
2. Run the ``` sudo SecureTea.py --system-mode ``` command
3. The output ``` Do you want to use the saved configuratons? (Y/y): ``` will not accept any strings.

**Detailed Log**
``` sudo SecureTea.py --system-mode
[!] Do you want to use the saved configuratons? (Y/y): Y
Traceback (most recent call last):
  File "/usr/local/bin/SecureTea.py", line 4, in <module>
    __import__('pkg_resources').run_script('securetea==1.5.1', 'SecureTea.py')
  File "/home/kevin-yob/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/kevin-yob/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1453, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/securetea-1.5.1-py2.7.egg/EGG-INFO/scripts/SecureTea.py", line 13, in <module>
    secT = SecureTea()
  File "/usr/local/lib/python2.7/dist-packages/securetea-1.5.1-py2.7.egg/securetea/core.py", line 77, in __init__
    args_dict = argsHelper.check_args()
  File "/usr/local/lib/python2.7/dist-packages/securetea-1.5.1-py2.7.egg/securetea/args/args_helper.py", line 689, in check_args
    config_decision = str(input("[!] Do you want to use the saved configuratons? (Y/y): "))
  File "<string>", line 1, in <module>
NameError: name 'Y' is not defined
```

**Screenshots**
![Screenshot from 2019-08-15 21-40-25](https://user-images.githubusercontent.com/46342897/63110362-df1ad780-bfa8-11e9-8c12-7b8aaf497152.png)

**Desktop :**
 - Operating System:  Ubuntu
 - OS version:  18.10

**Comment by abhisharma404** [comment]
@kevinshaji97 Which version of Python are you using?

**Comment by abhisharma404** [comment]
@kevinshaji97 I tried reproducing it but I could not! From what I can read from the error, seems like Python 2.7 type error, because of `raw_input` in Python. I'll downgrade my Python to 2.7 and try to reproduce the error, if done, I'll push in a patch by tomorrow. Meanwhile, could you please try by upgrading your python version to 3.6 the least and try installing again using the following steps:
```
git clone https://github.com/OWASP/SecureTea-Project.git
cd SecureTea-Project
sudo python3 -m pip install -r requirements.txt
sudo python3 setup.py install
```

**Comment by abhisharma404** [comment]
@kevinshaji97 Thanks a lot for bringing up this issue. As guessed, this error was due to Python 2 lost support. I have sent  a patch which will fix this, I have checked it thoroughly by deprecating my Python version. Please try to install again, as `requirements` have been updated. Use my remote branch for installing:
https://github.com/abhisharma404/SecureTea-Project/tree/bug-fix-229
